##### devcontainer 用の Docker Compose 定義ファイル #####

# name指定することで生成されるコンテナ名をある程度制御可能
# {name指定内容}-{service名} の形式にできる
name: lua-sqlite-development

services:
  ### devcontainer ###
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      # Forwards the local Docker socket to the container.
      - /var/run/docker.sock:/var/run/docker-host.sock
      # * プロジェクトルートの一つ上のディレクトリを/workspacesにマウントする設定
      # * ホスト側でのディレクトリ構成は以下のようにすること
      #   ```
      #   grandparents/
      #     parents1/ <- この配下に置かれているものが全部コンテナに取り込まれてしまう
      #       lua-sqlite/        <- devcontainerプロジェクト, これだけ配置する
      #     parents2/
      #       other-devcontainer-project/ <- 他のdevcontainerプロジェクト
      #   ```
      #
      # ! `/home/(user)/devcontainer-project` といった配置にしてしまうと
      # ! `/home/(user)/` 配下の全てのディレクトリ・ファイルがコンテナに取り込まれてしまうため注意
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    entrypoint: /usr/local/share/docker-init.sh
    command: sleep infinity

    # devcontainer 内から、動作確認用で動いている本番コンテナー等にアクセスするための設定
    extra_hosts:
      - "host.docker.internal:host-gateway"

    # ! 本番環境(AWSなりAzureなりGCPなり)にデプロイする際は、ENVが外部から設定できるはずなので
    # ! 以下のキーに相当する環境変数を本番環境に設定しておくこと
    environment:
      ## Honoのリッスンポート
      # 環境ごとに変えれるようにしておくと、prodイメージのローカル確認が楽になる
      - HONO_SERVICE_PORT=8000
